apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata: 
  lables:
    env: prf-usw2
  name: token-test-rollout
spec: 
  replicas: null
  revisionHistoryLimit: 2
  selector: 
    matchLabels: 
      app: token-test
  strategy: 
    canary: 
      analysis: 
      canaryMetadata: 
        labels: 
          state: canary
      canaryService: token-test-preview-service
      maxUnavailable: 0
      stableMetadata: 
        labels: 
          state: stable
      stableService: token-test-active-service
      analysis:
        templates:
        - templateName: success-rate
        args:
        - name: app-name
          value: token-test
        - name: pod-hash
          valueFrom:
            podTemplateHashValue: Latest

       
        - name: env
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['env']
      steps: 
        - 
          setCanaryScale: 
            replicas: 1
        - 
          pause: {}
        - 
          setWeight: 5
        - 
          setCanaryScale: 
            matchTrafficWeight: true
        - 
          pause: 
            duration: 30s
        - 
          setWeight: 20
        - 
          pause: 
            duration: 30s
        - 
          setWeight: 50
        - 
          pause: 
            duration: 30s
      trafficRouting: 
        nginx: 
          stableIngress: token-test-ingress
  template: 
    metadata: 
      labels: 
        app: token-test
    spec: 
      containers: 
        - 
          image: "token-service:attempt5"
          name: app
          ports: 
            - 
              containerPort: 8443
          resources: 
            requests: 
              cpu: 20m
              memory: 40Mi
