kind: Service
apiVersion: v1
metadata:
  labels:
    iks-metric: actuator-prometheus
  name: service-metrics
 spec:
    ports:
    - name: iks-metric
    port: 
    targetPort: 
  selector:
     app: 
